#pragma once

// Iris command and telemetry protocol definitions.
// Multi-byte field byte order is defined as big-endian on the wire.

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#define IRIS_COMMAND_ARGUMENT_LENGTH 0U

#define IRIS_COMMAND_CH1_LOAD_OFF 0x30U
#define IRIS_COMMAND_CH1_LOAD_ON 0x31U
#define IRIS_COMMAND_CH2_LOAD_OFF 0x32U
#define IRIS_COMMAND_CH2_LOAD_ON 0x33U
#define IRIS_COMMAND_CH3_LOAD_OFF 0x34U
#define IRIS_COMMAND_CH3_LOAD_ON 0x35U

#define IRIS_COMMAND_5V_REGULATOR_OFF 0x50U
#define IRIS_COMMAND_5V_REGULATOR_ON 0x51U

// ---------------------------------------------------------------------------
// Common packet fields
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_LENGTH 1U
#define IRIS_PACKET_CRC_LENGTH 2U
#define IRIS_PACKET_STATUS_LENGTH 2U
#define IRIS_PACKET_UPTIME_LENGTH 4U

// ---------------------------------------------------------------------------
// Sensor packet (10 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_SENSORS 0x01U
#define IRIS_PACKET_SENSORS_DATA_LENGTH 18U
#define IRIS_PACKET_SENSORS_WIRE_LENGTH \
    (IRIS_PACKET_SENSORS_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_SENSORS_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_SENSORS_WIRE_LENGTH)

#define IRIS_PACKET_SENSORS_STATUS_OFFSET 0U
#define IRIS_PACKET_SENSORS_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_SENSORS_UPTIME_OFFSET 2U
#define IRIS_PACKET_SENSORS_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_SENSORS_ACCEL_OFFSET 6U
#define IRIS_PACKET_SENSORS_ACCEL_LENGTH 6U
#define IRIS_PACKET_SENSORS_GYRO_OFFSET 12U
#define IRIS_PACKET_SENSORS_GYRO_LENGTH 6U
#define IRIS_PACKET_SENSORS_CRC_OFFSET IRIS_PACKET_SENSORS_DATA_LENGTH

// ---------------------------------------------------------------------------
// Estimated state and GPS packet (nominally 2 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_STATE 0x02U
#define IRIS_PACKET_STATE_DATA_LENGTH 47U
#define IRIS_PACKET_STATE_WIRE_LENGTH \
    (IRIS_PACKET_STATE_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_STATE_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_STATE_WIRE_LENGTH)

#define IRIS_PACKET_STATE_STATUS_OFFSET 0U
#define IRIS_PACKET_STATE_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_STATE_UPTIME_OFFSET 2U
#define IRIS_PACKET_STATE_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_STATE_ORIENTATION_OFFSET 6U
#define IRIS_PACKET_STATE_ORIENTATION_LENGTH 8U
#define IRIS_PACKET_STATE_POSITION_OFFSET 14U
#define IRIS_PACKET_STATE_POSITION_LENGTH 12U
#define IRIS_PACKET_STATE_VELOCITY_OFFSET 26U
#define IRIS_PACKET_STATE_VELOCITY_LENGTH 12U
#define IRIS_PACKET_STATE_LAT_LON_OFFSET 38U
#define IRIS_PACKET_STATE_LAT_LON_LENGTH 6U
#define IRIS_PACKET_STATE_GPS_ALTITUDE_OFFSET 44U
#define IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH 3U
#define IRIS_PACKET_STATE_CRC_OFFSET IRIS_PACKET_STATE_DATA_LENGTH

// ---------------------------------------------------------------------------
// Camera telemetry packet (1 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_CAMERA 0x03U
#define IRIS_PACKET_CAMERA_DATA_LENGTH 16U
#define IRIS_PACKET_CAMERA_WIRE_LENGTH \
    (IRIS_PACKET_CAMERA_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_CAMERA_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_CAMERA_WIRE_LENGTH)

#define IRIS_PACKET_CAMERA_FC_STATUS_OFFSET 0U
#define IRIS_PACKET_CAMERA_FC_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_CAMERA_FC_UPTIME_OFFSET 2U
#define IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_CAMERA_STATUS_OFFSET 6U
#define IRIS_PACKET_CAMERA_STATUS_LENGTH 2U
#define IRIS_PACKET_CAMERA_UPTIME_OFFSET 8U
#define IRIS_PACKET_CAMERA_UPTIME_LENGTH 4U
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET 12U
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH 4U
#define IRIS_PACKET_CAMERA_CRC_OFFSET IRIS_PACKET_CAMERA_DATA_LENGTH

// ---------------------------------------------------------------------------
// Ground-station heartbeat packet
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_HEARTBEAT 0xFFU
#define IRIS_PACKET_HEARTBEAT_DATA_LENGTH 6U
#define IRIS_PACKET_HEARTBEAT_WIRE_LENGTH IRIS_PACKET_HEARTBEAT_DATA_LENGTH
#define IRIS_PACKET_HEARTBEAT_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_HEARTBEAT_WIRE_LENGTH)

#define IRIS_PACKET_HEARTBEAT_STATUS_OFFSET 0U
#define IRIS_PACKET_HEARTBEAT_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_HEARTBEAT_UPTIME_OFFSET 2U
#define IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH

