#pragma once

// AMA command and telemetry protocol definitions from
// "AMA_comms_standard.xlsx".
//
// Every transport uses the same canonical application packet:
//
//     packet ID | fixed-layout payload | 0x0A end-of-frame delimiter
//
// The delimiter is not escaped and may occur in binary payload data. A receiver
// must therefore determine the payload length from the packet ID and verify the
// delimiter at the resulting fixed offset; it must not scan for 0x0A. Transport
// framing, integrity checks, and CAN fragmentation are outside this schema.
// Multi-byte fields are big-endian on the wire.

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#define IRIS_COMMAND_ARGUMENT_LENGTH 0U

#define IRIS_COMMAND_STATUS_FLAG_SET 0x20U
#define IRIS_COMMAND_STATUS_FLAG_CLEAR 0x21U
#define IRIS_COMMAND_PING 0x22U
#define IRIS_COMMAND_PONG 0x23U

#define IRIS_COMMAND_CH1_LOAD_OFF 0x30U
#define IRIS_COMMAND_CH1_LOAD_ON 0x31U
#define IRIS_COMMAND_CH2_LOAD_OFF 0x32U
#define IRIS_COMMAND_CH2_LOAD_ON 0x33U
#define IRIS_COMMAND_CH3_LOAD_OFF 0x34U
#define IRIS_COMMAND_CH3_LOAD_ON 0x35U

#define IRIS_COMMAND_5V_REGULATOR_OFF 0x50U
#define IRIS_COMMAND_5V_REGULATOR_ON 0x51U

#define IRIS_COMMAND_IRIS_DEBUG_START 0xE1U

// Producer-defined IRIS status-byte flags.
#define IRIS_STATUS_CURRENT_MONITOR_ERROR_FLAG 0x01U
#define IRIS_STATUS_BATTERY_MONITOR_ERROR_FLAG 0x02U
#define IRIS_STATUS_COMMAND_CONTROLLED_FLAG 0x04U
#define IRIS_STATUS_OUT1_ENABLED_FLAG 0x08U
#define IRIS_STATUS_OUT2_ENABLED_FLAG 0x10U
#define IRIS_STATUS_OUT3_ENABLED_FLAG 0x20U
#define IRIS_STATUS_5V_ENABLED_FLAG 0x40U

// ---------------------------------------------------------------------------
// Canonical field catalog
// ---------------------------------------------------------------------------

// Witness status: two raw flag bytes. Byte 0 contains producer-defined active
// flags and byte 1 is reserved. This is not a scaled numeric quantity.
#define IRIS_FIELD_WITNESS_STATUS_LENGTH 2U

// Witness uptime: big-endian uint32, milliseconds since boot. The counter
// wraps after approximately 49.7 days.
#define IRIS_FIELD_WITNESS_UPTIME_LENGTH 4U

// Witness MCU temperature: signed int8, 1 degree Celsius/count.
#define IRIS_FIELD_WITNESS_MCU_TEMPERATURE_LENGTH 1U

// Witness battery voltage: big-endian uint16, 1 millivolt/count.
#define IRIS_FIELD_WITNESS_BATTERY_VOLTAGE_LENGTH 2U

// IRIS uptime: big-endian uint32, milliseconds since boot. The counter wraps
// after approximately 49.7 days.
#define IRIS_FIELD_IRIS_UPTIME_LENGTH 4U

// IRIS status: two raw flag bytes. Byte 0 contains producer-defined active
// flags and byte 1 is reserved. This is not a scaled numeric quantity.
#define IRIS_FIELD_IRIS_STATUS_LENGTH 2U

// IRIS MCU temperature: signed int8, 1 degree Celsius/count.
#define IRIS_FIELD_IRIS_MCU_TEMPERATURE_LENGTH 1U

// IRIS battery voltage: big-endian uint16, 1 millivolt/count.
#define IRIS_FIELD_IRIS_BATTERY_VOLTAGE_LENGTH 2U

// Filtered acceleration: big-endian signed int24, 40 micro-g/count. Physical
// acceleration in g = raw * 0.000040. Range is approximately +/-335.54 g.
#define IRIS_FIELD_FILTERED_ACCEL_X_LENGTH 3U
#define IRIS_FIELD_FILTERED_ACCEL_Y_LENGTH 3U
#define IRIS_FIELD_FILTERED_ACCEL_Z_LENGTH 3U

// Orientation quaternion: big-endian IEEE-754 float32, unitless normalized
// quaternion components in X, Y, Z, W order. Coordinate-frame convention is
// estimator-defined and must be shared separately by producers and consumers.
#define IRIS_FIELD_ORIENTATION_QUAT_X_LENGTH 4U
#define IRIS_FIELD_ORIENTATION_QUAT_Y_LENGTH 4U
#define IRIS_FIELD_ORIENTATION_QUAT_Z_LENGTH 4U
#define IRIS_FIELD_ORIENTATION_QUAT_W_LENGTH 4U

// Position: big-endian IEEE-754 float32, meters in the estimator local frame.
// The local-frame origin and axis convention are estimator-defined.
#define IRIS_FIELD_POSITION_X_LENGTH 4U
#define IRIS_FIELD_POSITION_Y_LENGTH 4U
#define IRIS_FIELD_POSITION_Z_LENGTH 4U

// Velocity: big-endian IEEE-754 float32, meters/second in the estimator local
// frame. Axis convention matches the position field.
#define IRIS_FIELD_VELOCITY_X_LENGTH 4U
#define IRIS_FIELD_VELOCITY_Y_LENGTH 4U
#define IRIS_FIELD_VELOCITY_Z_LENGTH 4U

// LSM6 low-g acceleration: big-endian signed int16 native sensor samples,
// 0.488 milli-g/count at the configured +/-16 g full scale.
#define IRIS_FIELD_LSM6_LOW_ACCEL_X_LENGTH 2U
#define IRIS_FIELD_LSM6_LOW_ACCEL_Y_LENGTH 2U
#define IRIS_FIELD_LSM6_LOW_ACCEL_Z_LENGTH 2U

// LSM6 temperature: big-endian signed int16 native sensor sample.
// Temperature in degrees Celsius = 25 + raw / 256.
#define IRIS_FIELD_LSM6_TEMPERATURE_LENGTH 2U

// LSM6 high-g acceleration: big-endian signed int16 native sensor samples,
// 10.417 milli-g/count at the configured +/-320 g full scale.
#define IRIS_FIELD_LSM6_HIGH_ACCEL_X_LENGTH 2U
#define IRIS_FIELD_LSM6_HIGH_ACCEL_Y_LENGTH 2U
#define IRIS_FIELD_LSM6_HIGH_ACCEL_Z_LENGTH 2U

// LSM6 angular rate: big-endian signed int16 native sensor samples,
// 70 milli-degrees/second/count at the configured +/-2000 dps full scale.
#define IRIS_FIELD_LSM6_GYRO_X_LENGTH 2U
#define IRIS_FIELD_LSM6_GYRO_Y_LENGTH 2U
#define IRIS_FIELD_LSM6_GYRO_Z_LENGTH 2U

// MS5607 pressure: big-endian unsigned uint24, 1 pascal/count. One pascal is
// equivalent to 0.01 millibar, matching the driver's centi-mbar value.
#define IRIS_FIELD_MS5607_PRESSURE_LENGTH 3U

// MS5607 temperature: big-endian signed int16, 0.01 degree Celsius/count.
#define IRIS_FIELD_MS5607_TEMPERATURE_LENGTH 2U

// MS5607 altitude: big-endian IEEE-754 float32, meters relative to the
// configured sea-level pressure reference (currently 1013.25 mbar).
#define IRIS_FIELD_MS5607_ALTITUDE_LENGTH 4U

// Latitude and longitude: big-endian signed int24, 0.0001 degree/count.
// Degrees = raw / 10,000; north/east are positive and south/west negative.
#define IRIS_FIELD_LATITUDE_LENGTH 3U
#define IRIS_FIELD_LONGITUDE_LENGTH 3U

// GPS time: big-endian uint32 Unix timestamp, seconds since 1970-01-01 UTC.
#define IRIS_FIELD_GPS_TIME_LENGTH 4U

// GPS altitude: big-endian IEEE-754 float32, meters above mean sea level.
#define IRIS_FIELD_GPS_ALTITUDE_LENGTH 4U

// Channel current: unsigned uint8, 0.1 ampere/count (100 mA/count).
// Representable range is 0.0 to 25.5 A.
#define IRIS_FIELD_CH1_CURRENT_LENGTH 1U
#define IRIS_FIELD_CH2_CURRENT_LENGTH 1U
#define IRIS_FIELD_CH3_CURRENT_LENGTH 1U

// Command: big-endian uint16 enumeration/opcode. No numeric scale or unit.
#define IRIS_FIELD_COMMAND_LENGTH 2U

// Machine-readable fixed-point scales corresponding to the comments above.
#define IRIS_FIELD_FILTERED_ACCEL_MICRO_G_PER_COUNT 40U
#define IRIS_FIELD_BATTERY_VOLTAGE_MILLIVOLTS_PER_COUNT 1U
#define IRIS_FIELD_GPS_COORDINATE_SCALE 10000L
#define IRIS_FIELD_MCU_TEMPERATURE_CELSIUS_PER_COUNT 1U
#define IRIS_FIELD_LSM6_LOW_ACCEL_MICRO_G_PER_COUNT 488U
#define IRIS_FIELD_LSM6_HIGH_ACCEL_MICRO_G_PER_COUNT 10417U
#define IRIS_FIELD_LSM6_GYRO_MILLIDEGREES_PER_SECOND_PER_COUNT 70U
#define IRIS_FIELD_LSM6_TEMPERATURE_RAW_COUNTS_PER_CELSIUS 256U
#define IRIS_FIELD_LSM6_TEMPERATURE_OFFSET_CENTICELSIUS 2500
#define IRIS_FIELD_MS5607_PRESSURE_PASCALS_PER_COUNT 1U
#define IRIS_FIELD_MS5607_TEMPERATURE_CENTICELSIUS_PER_COUNT 1U
#define IRIS_FIELD_CURRENT_MILLIAMPS_PER_COUNT 100U

// ---------------------------------------------------------------------------
// Common packet definitions
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_LENGTH 1U
#define IRIS_PACKET_EOF_VALUE 0x0AU
#define IRIS_PACKET_EOF_LENGTH 1U
#define IRIS_PACKET_TRANSPORT_CRC_LENGTH 0U
#define IRIS_CAN_FRAME_DATA_LENGTH 8U
#define IRIS_CAN_FRAME_COUNT(application_packet_length) \
    (((application_packet_length) + IRIS_CAN_FRAME_DATA_LENGTH - 1U) / \
     IRIS_CAN_FRAME_DATA_LENGTH)
// Packet-level status and uptime aliases use the Witness encodings documented
// above: two raw flag bytes and big-endian uint32 milliseconds, respectively.
#define IRIS_PACKET_STATUS_LENGTH IRIS_FIELD_WITNESS_STATUS_LENGTH
#define IRIS_PACKET_UPTIME_LENGTH IRIS_FIELD_WITNESS_UPTIME_LENGTH

#define IRIS_PACKET_VECTOR_COMPONENTS 3U
#define IRIS_PACKET_QUATERNION_COMPONENTS 4U
#define IRIS_PACKET_CAMERA_CURRENT_CHANNELS 3U

// ---------------------------------------------------------------------------
// Sensor packet (0x01)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_SENSORS 0x01U

#define IRIS_PACKET_SENSORS_STATUS_OFFSET 0U
#define IRIS_PACKET_SENSORS_STATUS_LENGTH IRIS_FIELD_WITNESS_STATUS_LENGTH
#define IRIS_PACKET_SENSORS_UPTIME_OFFSET \
    (IRIS_PACKET_SENSORS_STATUS_OFFSET + IRIS_PACKET_SENSORS_STATUS_LENGTH)
#define IRIS_PACKET_SENSORS_UPTIME_LENGTH IRIS_FIELD_WITNESS_UPTIME_LENGTH
#define IRIS_PACKET_SENSORS_ACCEL_OFFSET \
    (IRIS_PACKET_SENSORS_UPTIME_OFFSET + IRIS_PACKET_SENSORS_UPTIME_LENGTH)
#define IRIS_PACKET_SENSORS_ACCEL_COMPONENT_LENGTH \
    IRIS_FIELD_FILTERED_ACCEL_X_LENGTH
#define IRIS_PACKET_SENSORS_ACCEL_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * \
     IRIS_PACKET_SENSORS_ACCEL_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_ACCEL_X_OFFSET IRIS_PACKET_SENSORS_ACCEL_OFFSET
#define IRIS_PACKET_SENSORS_ACCEL_Y_OFFSET \
    (IRIS_PACKET_SENSORS_ACCEL_X_OFFSET + \
     IRIS_PACKET_SENSORS_ACCEL_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_ACCEL_Z_OFFSET \
    (IRIS_PACKET_SENSORS_ACCEL_Y_OFFSET + \
     IRIS_PACKET_SENSORS_ACCEL_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_OFFSET \
    (IRIS_PACKET_SENSORS_ACCEL_OFFSET + IRIS_PACKET_SENSORS_ACCEL_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_COMPONENT_LENGTH \
    IRIS_FIELD_LSM6_GYRO_X_LENGTH
#define IRIS_PACKET_SENSORS_GYRO_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * \
     IRIS_PACKET_SENSORS_GYRO_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_X_OFFSET IRIS_PACKET_SENSORS_GYRO_OFFSET
#define IRIS_PACKET_SENSORS_GYRO_Y_OFFSET \
    (IRIS_PACKET_SENSORS_GYRO_X_OFFSET + \
     IRIS_PACKET_SENSORS_GYRO_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_Z_OFFSET \
    (IRIS_PACKET_SENSORS_GYRO_Y_OFFSET + \
     IRIS_PACKET_SENSORS_GYRO_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_DATA_LENGTH \
    (IRIS_PACKET_SENSORS_STATUS_LENGTH + \
     IRIS_PACKET_SENSORS_UPTIME_LENGTH + \
     IRIS_PACKET_SENSORS_ACCEL_LENGTH + \
     IRIS_PACKET_SENSORS_GYRO_LENGTH)
#define IRIS_PACKET_SENSORS_EOF_OFFSET IRIS_PACKET_SENSORS_DATA_LENGTH
#define IRIS_PACKET_SENSORS_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_SENSORS_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_SENSORS_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_SENSORS_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// Estimated-state packet (0x02)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_STATE 0x02U

#define IRIS_PACKET_STATE_STATUS_OFFSET 0U
#define IRIS_PACKET_STATE_STATUS_LENGTH IRIS_FIELD_WITNESS_STATUS_LENGTH
#define IRIS_PACKET_STATE_UPTIME_OFFSET \
    (IRIS_PACKET_STATE_STATUS_OFFSET + IRIS_PACKET_STATE_STATUS_LENGTH)
#define IRIS_PACKET_STATE_UPTIME_LENGTH IRIS_FIELD_WITNESS_UPTIME_LENGTH
#define IRIS_PACKET_STATE_ORIENTATION_OFFSET \
    (IRIS_PACKET_STATE_UPTIME_OFFSET + IRIS_PACKET_STATE_UPTIME_LENGTH)
#define IRIS_PACKET_STATE_ORIENTATION_COMPONENT_LENGTH \
    IRIS_FIELD_ORIENTATION_QUAT_X_LENGTH
#define IRIS_PACKET_STATE_ORIENTATION_LENGTH \
    (IRIS_PACKET_QUATERNION_COMPONENTS * \
     IRIS_PACKET_STATE_ORIENTATION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_ORIENTATION_X_OFFSET \
    IRIS_PACKET_STATE_ORIENTATION_OFFSET
#define IRIS_PACKET_STATE_ORIENTATION_Y_OFFSET \
    (IRIS_PACKET_STATE_ORIENTATION_X_OFFSET + \
     IRIS_PACKET_STATE_ORIENTATION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_ORIENTATION_Z_OFFSET \
    (IRIS_PACKET_STATE_ORIENTATION_Y_OFFSET + \
     IRIS_PACKET_STATE_ORIENTATION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_ORIENTATION_W_OFFSET \
    (IRIS_PACKET_STATE_ORIENTATION_Z_OFFSET + \
     IRIS_PACKET_STATE_ORIENTATION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_POSITION_OFFSET \
    (IRIS_PACKET_STATE_ORIENTATION_OFFSET + \
     IRIS_PACKET_STATE_ORIENTATION_LENGTH)
#define IRIS_PACKET_STATE_POSITION_COMPONENT_LENGTH IRIS_FIELD_POSITION_X_LENGTH
#define IRIS_PACKET_STATE_POSITION_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * \
     IRIS_PACKET_STATE_POSITION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_POSITION_X_OFFSET IRIS_PACKET_STATE_POSITION_OFFSET
#define IRIS_PACKET_STATE_POSITION_Y_OFFSET \
    (IRIS_PACKET_STATE_POSITION_X_OFFSET + \
     IRIS_PACKET_STATE_POSITION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_POSITION_Z_OFFSET \
    (IRIS_PACKET_STATE_POSITION_Y_OFFSET + \
     IRIS_PACKET_STATE_POSITION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_OFFSET \
    (IRIS_PACKET_STATE_POSITION_OFFSET + IRIS_PACKET_STATE_POSITION_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_COMPONENT_LENGTH IRIS_FIELD_VELOCITY_X_LENGTH
#define IRIS_PACKET_STATE_VELOCITY_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * \
     IRIS_PACKET_STATE_VELOCITY_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_X_OFFSET IRIS_PACKET_STATE_VELOCITY_OFFSET
#define IRIS_PACKET_STATE_VELOCITY_Y_OFFSET \
    (IRIS_PACKET_STATE_VELOCITY_X_OFFSET + \
     IRIS_PACKET_STATE_VELOCITY_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_Z_OFFSET \
    (IRIS_PACKET_STATE_VELOCITY_Y_OFFSET + \
     IRIS_PACKET_STATE_VELOCITY_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_LATITUDE_OFFSET \
    (IRIS_PACKET_STATE_VELOCITY_OFFSET + IRIS_PACKET_STATE_VELOCITY_LENGTH)
#define IRIS_PACKET_STATE_LATITUDE_LENGTH IRIS_FIELD_LATITUDE_LENGTH
#define IRIS_PACKET_STATE_LONGITUDE_OFFSET \
    (IRIS_PACKET_STATE_LATITUDE_OFFSET + IRIS_PACKET_STATE_LATITUDE_LENGTH)
#define IRIS_PACKET_STATE_LONGITUDE_LENGTH IRIS_FIELD_LONGITUDE_LENGTH
#define IRIS_PACKET_STATE_LAT_LON_OFFSET IRIS_PACKET_STATE_LATITUDE_OFFSET
#define IRIS_PACKET_STATE_LAT_LON_LENGTH \
    (IRIS_PACKET_STATE_LATITUDE_LENGTH + IRIS_PACKET_STATE_LONGITUDE_LENGTH)
#define IRIS_PACKET_STATE_GPS_ALTITUDE_OFFSET \
    (IRIS_PACKET_STATE_LONGITUDE_OFFSET + IRIS_PACKET_STATE_LONGITUDE_LENGTH)
#define IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH IRIS_FIELD_GPS_ALTITUDE_LENGTH
#define IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_OFFSET \
    (IRIS_PACKET_STATE_GPS_ALTITUDE_OFFSET + \
     IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH)
#define IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH \
    IRIS_FIELD_MS5607_ALTITUDE_LENGTH
#define IRIS_PACKET_STATE_BATTERY_VOLTAGE_OFFSET \
    (IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_OFFSET + \
     IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH)
#define IRIS_PACKET_STATE_BATTERY_VOLTAGE_LENGTH \
    IRIS_FIELD_WITNESS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_STATE_DATA_LENGTH \
    (IRIS_PACKET_STATE_STATUS_LENGTH + \
     IRIS_PACKET_STATE_UPTIME_LENGTH + \
     IRIS_PACKET_STATE_ORIENTATION_LENGTH + \
     IRIS_PACKET_STATE_POSITION_LENGTH + \
     IRIS_PACKET_STATE_VELOCITY_LENGTH + \
     IRIS_PACKET_STATE_LATITUDE_LENGTH + \
     IRIS_PACKET_STATE_LONGITUDE_LENGTH + \
     IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH + \
     IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH + \
     IRIS_PACKET_STATE_BATTERY_VOLTAGE_LENGTH)
#define IRIS_PACKET_STATE_EOF_OFFSET IRIS_PACKET_STATE_DATA_LENGTH
#define IRIS_PACKET_STATE_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_STATE_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_STATE_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_STATE_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// Camera telemetry packet (0x03)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_CAMERA 0x03U

#define IRIS_PACKET_CAMERA_FC_STATUS_OFFSET 0U
#define IRIS_PACKET_CAMERA_FC_STATUS_LENGTH IRIS_FIELD_WITNESS_STATUS_LENGTH
#define IRIS_PACKET_CAMERA_FC_UPTIME_OFFSET \
    (IRIS_PACKET_CAMERA_FC_STATUS_OFFSET + \
     IRIS_PACKET_CAMERA_FC_STATUS_LENGTH)
#define IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH IRIS_FIELD_WITNESS_UPTIME_LENGTH
#define IRIS_PACKET_CAMERA_STATUS_OFFSET \
    (IRIS_PACKET_CAMERA_FC_UPTIME_OFFSET + \
     IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH)
#define IRIS_PACKET_CAMERA_STATUS_LENGTH IRIS_FIELD_IRIS_STATUS_LENGTH
#define IRIS_PACKET_CAMERA_UPTIME_OFFSET \
    (IRIS_PACKET_CAMERA_STATUS_OFFSET + IRIS_PACKET_CAMERA_STATUS_LENGTH)
#define IRIS_PACKET_CAMERA_UPTIME_LENGTH IRIS_FIELD_IRIS_UPTIME_LENGTH
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET \
    (IRIS_PACKET_CAMERA_UPTIME_OFFSET + IRIS_PACKET_CAMERA_UPTIME_LENGTH)
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_COMPONENT_LENGTH \
    IRIS_FIELD_CH1_CURRENT_LENGTH
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH \
    (IRIS_PACKET_CAMERA_CURRENT_CHANNELS * \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_COMPONENT_LENGTH)
#define IRIS_PACKET_CAMERA_CH1_CURRENT_OFFSET \
    IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET
#define IRIS_PACKET_CAMERA_CH2_CURRENT_OFFSET \
    (IRIS_PACKET_CAMERA_CH1_CURRENT_OFFSET + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_COMPONENT_LENGTH)
#define IRIS_PACKET_CAMERA_CH3_CURRENT_OFFSET \
    (IRIS_PACKET_CAMERA_CH2_CURRENT_OFFSET + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_COMPONENT_LENGTH)
#define IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_OFFSET \
    (IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH)
#define IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_LENGTH \
    IRIS_FIELD_IRIS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_CAMERA_DATA_LENGTH \
    (IRIS_PACKET_CAMERA_FC_STATUS_LENGTH + \
     IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH + \
     IRIS_PACKET_CAMERA_STATUS_LENGTH + \
     IRIS_PACKET_CAMERA_UPTIME_LENGTH + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH + \
     IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_LENGTH)
#define IRIS_PACKET_CAMERA_EOF_OFFSET IRIS_PACKET_CAMERA_DATA_LENGTH
#define IRIS_PACKET_CAMERA_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_CAMERA_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_CAMERA_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_CAMERA_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// Command packet (0x05)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_COMMAND 0x05U

#define IRIS_PACKET_COMMAND_STATUS_OFFSET 0U
#define IRIS_PACKET_COMMAND_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_COMMAND_UPTIME_OFFSET \
    (IRIS_PACKET_COMMAND_STATUS_OFFSET + IRIS_PACKET_COMMAND_STATUS_LENGTH)
#define IRIS_PACKET_COMMAND_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_COMMAND_VALUE_OFFSET \
    (IRIS_PACKET_COMMAND_UPTIME_OFFSET + IRIS_PACKET_COMMAND_UPTIME_LENGTH)
#define IRIS_PACKET_COMMAND_VALUE_LENGTH IRIS_FIELD_COMMAND_LENGTH
#define IRIS_PACKET_COMMAND_DATA_LENGTH \
    (IRIS_PACKET_COMMAND_STATUS_LENGTH + \
     IRIS_PACKET_COMMAND_UPTIME_LENGTH + \
     IRIS_PACKET_COMMAND_VALUE_LENGTH)
#define IRIS_PACKET_COMMAND_EOF_OFFSET IRIS_PACKET_COMMAND_DATA_LENGTH
#define IRIS_PACKET_COMMAND_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_COMMAND_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_COMMAND_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_COMMAND_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// Heartbeat packet (0xFF)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_HEARTBEAT 0xFFU

#define IRIS_PACKET_HEARTBEAT_STATUS_OFFSET 0U
#define IRIS_PACKET_HEARTBEAT_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_HEARTBEAT_UPTIME_OFFSET \
    (IRIS_PACKET_HEARTBEAT_STATUS_OFFSET + \
     IRIS_PACKET_HEARTBEAT_STATUS_LENGTH)
#define IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_HEARTBEAT_DATA_LENGTH \
    (IRIS_PACKET_HEARTBEAT_STATUS_LENGTH + \
     IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH)
#define IRIS_PACKET_HEARTBEAT_EOF_OFFSET IRIS_PACKET_HEARTBEAT_DATA_LENGTH
#define IRIS_PACKET_HEARTBEAT_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_HEARTBEAT_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_HEARTBEAT_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_HEARTBEAT_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// Witness debug packet (0xE0)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_WITNESS_DEBUG 0xE0U

#define IRIS_PACKET_WITNESS_DEBUG_STATUS_OFFSET 0U
#define IRIS_PACKET_WITNESS_DEBUG_STATUS_LENGTH \
    IRIS_FIELD_WITNESS_STATUS_LENGTH
#define IRIS_PACKET_WITNESS_DEBUG_UPTIME_OFFSET 2U
#define IRIS_PACKET_WITNESS_DEBUG_UPTIME_LENGTH \
    IRIS_FIELD_WITNESS_UPTIME_LENGTH
#define IRIS_PACKET_WITNESS_DEBUG_MCU_TEMPERATURE_OFFSET 6U
#define IRIS_PACKET_WITNESS_DEBUG_MCU_TEMPERATURE_LENGTH \
    IRIS_FIELD_WITNESS_MCU_TEMPERATURE_LENGTH
#define IRIS_PACKET_WITNESS_DEBUG_BATTERY_VOLTAGE_OFFSET 7U
#define IRIS_PACKET_WITNESS_DEBUG_BATTERY_VOLTAGE_LENGTH \
    IRIS_FIELD_WITNESS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_WITNESS_DEBUG_FILTERED_ACCEL_X_OFFSET 9U
#define IRIS_PACKET_WITNESS_DEBUG_FILTERED_ACCEL_Y_OFFSET 12U
#define IRIS_PACKET_WITNESS_DEBUG_FILTERED_ACCEL_Z_OFFSET 15U
#define IRIS_PACKET_WITNESS_DEBUG_ORIENTATION_X_OFFSET 18U
#define IRIS_PACKET_WITNESS_DEBUG_ORIENTATION_Y_OFFSET 22U
#define IRIS_PACKET_WITNESS_DEBUG_ORIENTATION_Z_OFFSET 26U
#define IRIS_PACKET_WITNESS_DEBUG_ORIENTATION_W_OFFSET 30U
#define IRIS_PACKET_WITNESS_DEBUG_POSITION_X_OFFSET 34U
#define IRIS_PACKET_WITNESS_DEBUG_POSITION_Y_OFFSET 38U
#define IRIS_PACKET_WITNESS_DEBUG_POSITION_Z_OFFSET 42U
#define IRIS_PACKET_WITNESS_DEBUG_VELOCITY_X_OFFSET 46U
#define IRIS_PACKET_WITNESS_DEBUG_VELOCITY_Y_OFFSET 50U
#define IRIS_PACKET_WITNESS_DEBUG_VELOCITY_Z_OFFSET 54U
#define IRIS_PACKET_WITNESS_DEBUG_LOW_ACCEL_X_OFFSET 58U
#define IRIS_PACKET_WITNESS_DEBUG_LOW_ACCEL_Y_OFFSET 60U
#define IRIS_PACKET_WITNESS_DEBUG_LOW_ACCEL_Z_OFFSET 62U
#define IRIS_PACKET_WITNESS_DEBUG_LSM6_TEMPERATURE_OFFSET 64U
#define IRIS_PACKET_WITNESS_DEBUG_HIGH_ACCEL_X_OFFSET 66U
#define IRIS_PACKET_WITNESS_DEBUG_HIGH_ACCEL_Y_OFFSET 68U
#define IRIS_PACKET_WITNESS_DEBUG_HIGH_ACCEL_Z_OFFSET 70U
#define IRIS_PACKET_WITNESS_DEBUG_GYRO_X_OFFSET 72U
#define IRIS_PACKET_WITNESS_DEBUG_GYRO_Y_OFFSET 74U
#define IRIS_PACKET_WITNESS_DEBUG_GYRO_Z_OFFSET 76U
#define IRIS_PACKET_WITNESS_DEBUG_PRESSURE_OFFSET 78U
#define IRIS_PACKET_WITNESS_DEBUG_MS5607_TEMPERATURE_OFFSET 81U
#define IRIS_PACKET_WITNESS_DEBUG_BAROMETRIC_ALTITUDE_OFFSET 83U
#define IRIS_PACKET_WITNESS_DEBUG_LATITUDE_OFFSET 87U
#define IRIS_PACKET_WITNESS_DEBUG_LONGITUDE_OFFSET 90U
#define IRIS_PACKET_WITNESS_DEBUG_GPS_TIME_OFFSET 93U
#define IRIS_PACKET_WITNESS_DEBUG_GPS_ALTITUDE_OFFSET 97U
#define IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH 101U
#define IRIS_PACKET_WITNESS_DEBUG_EOF_OFFSET \
    IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH
#define IRIS_PACKET_WITNESS_DEBUG_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_WITNESS_DEBUG_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_WITNESS_DEBUG_FRAME_LENGTH)

// ---------------------------------------------------------------------------
// IRIS debug packet (0xE1)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_IRIS_DEBUG 0xE1U

#define IRIS_PACKET_IRIS_DEBUG_STATUS_OFFSET 0U
#define IRIS_PACKET_IRIS_DEBUG_STATUS_LENGTH IRIS_FIELD_IRIS_STATUS_LENGTH
#define IRIS_PACKET_IRIS_DEBUG_UPTIME_OFFSET 2U
#define IRIS_PACKET_IRIS_DEBUG_UPTIME_LENGTH IRIS_FIELD_IRIS_UPTIME_LENGTH
#define IRIS_PACKET_IRIS_DEBUG_MCU_TEMPERATURE_OFFSET 6U
#define IRIS_PACKET_IRIS_DEBUG_MCU_TEMPERATURE_LENGTH \
    IRIS_FIELD_IRIS_MCU_TEMPERATURE_LENGTH
#define IRIS_PACKET_IRIS_DEBUG_BATTERY_VOLTAGE_OFFSET 7U
#define IRIS_PACKET_IRIS_DEBUG_BATTERY_VOLTAGE_LENGTH \
    IRIS_FIELD_IRIS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_IRIS_DEBUG_CH1_CURRENT_OFFSET 9U
#define IRIS_PACKET_IRIS_DEBUG_CH2_CURRENT_OFFSET 10U
#define IRIS_PACKET_IRIS_DEBUG_CH3_CURRENT_OFFSET 11U
#define IRIS_PACKET_IRIS_DEBUG_DATA_LENGTH 12U
#define IRIS_PACKET_IRIS_DEBUG_EOF_OFFSET IRIS_PACKET_IRIS_DEBUG_DATA_LENGTH
#define IRIS_PACKET_IRIS_DEBUG_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_IRIS_DEBUG_DATA_LENGTH + \
     IRIS_PACKET_EOF_LENGTH)
#define IRIS_PACKET_IRIS_DEBUG_CAN_FRAME_COUNT \
    IRIS_CAN_FRAME_COUNT(IRIS_PACKET_IRIS_DEBUG_FRAME_LENGTH)

// Largest payload currently defined by the workbook. This excludes both the
// packet ID and EOF delimiter.
#define IRIS_PACKET_MAX_DATA_LENGTH IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH

// Catch accidental schema drift from the workbook totals. Payload lengths do
// not include the packet ID or EOF delimiter; frame lengths include both.
#if IRIS_PACKET_SENSORS_DATA_LENGTH != 21U
#error "Sensor packet payload must be 21 bytes"
#endif
#if IRIS_PACKET_STATE_DATA_LENGTH != 62U
#error "State packet payload must be 62 bytes"
#endif
#if IRIS_PACKET_CAMERA_DATA_LENGTH != 17U
#error "Camera packet payload must be 17 bytes"
#endif
#if IRIS_PACKET_COMMAND_DATA_LENGTH != 8U
#error "Command packet payload must be 8 bytes"
#endif
#if IRIS_PACKET_HEARTBEAT_DATA_LENGTH != 6U
#error "Heartbeat packet payload must be 6 bytes"
#endif
#if IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH != 101U
#error "Witness debug packet payload must be 101 bytes"
#endif
#if IRIS_PACKET_IRIS_DEBUG_DATA_LENGTH != 12U
#error "IRIS debug packet payload must be 12 bytes"
#endif
#if IRIS_PACKET_SENSORS_GYRO_Z_OFFSET + \
        IRIS_PACKET_SENSORS_GYRO_COMPONENT_LENGTH != \
    IRIS_PACKET_SENSORS_DATA_LENGTH
#error "Sensor packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_STATE_BATTERY_VOLTAGE_OFFSET + \
        IRIS_PACKET_STATE_BATTERY_VOLTAGE_LENGTH != \
    IRIS_PACKET_STATE_DATA_LENGTH
#error "State packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_OFFSET + \
        IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_LENGTH != \
    IRIS_PACKET_CAMERA_DATA_LENGTH
#error "Camera packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_COMMAND_VALUE_OFFSET + IRIS_PACKET_COMMAND_VALUE_LENGTH != \
    IRIS_PACKET_COMMAND_DATA_LENGTH
#error "Command packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_HEARTBEAT_UPTIME_OFFSET + \
        IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH != \
    IRIS_PACKET_HEARTBEAT_DATA_LENGTH
#error "Heartbeat packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_WITNESS_DEBUG_GPS_ALTITUDE_OFFSET + \
        IRIS_FIELD_GPS_ALTITUDE_LENGTH != \
    IRIS_PACKET_WITNESS_DEBUG_DATA_LENGTH
#error "Witness debug packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_IRIS_DEBUG_CH3_CURRENT_OFFSET + \
        IRIS_FIELD_CH3_CURRENT_LENGTH != \
    IRIS_PACKET_IRIS_DEBUG_DATA_LENGTH
#error "IRIS debug packet field offsets do not fill the payload"
#endif
#if IRIS_PACKET_SENSORS_FRAME_LENGTH != 23U
#error "Sensor application packet must be 23 bytes"
#endif
#if IRIS_PACKET_STATE_FRAME_LENGTH != 64U
#error "State application packet must be 64 bytes"
#endif
#if IRIS_PACKET_CAMERA_FRAME_LENGTH != 19U
#error "Camera application packet must be 19 bytes"
#endif
#if IRIS_PACKET_COMMAND_FRAME_LENGTH != 10U
#error "Command application packet must be 10 bytes"
#endif
#if IRIS_PACKET_HEARTBEAT_FRAME_LENGTH != 8U
#error "Heartbeat application packet must be 8 bytes"
#endif
#if IRIS_PACKET_WITNESS_DEBUG_FRAME_LENGTH != 103U
#error "Witness debug application packet must be 103 bytes"
#endif
#if IRIS_PACKET_IRIS_DEBUG_FRAME_LENGTH != 14U
#error "IRIS debug application packet must be 14 bytes"
#endif
#if IRIS_PACKET_SENSORS_CAN_FRAME_COUNT != 3U || \
    IRIS_PACKET_STATE_CAN_FRAME_COUNT != 8U || \
    IRIS_PACKET_CAMERA_CAN_FRAME_COUNT != 3U || \
    IRIS_PACKET_COMMAND_CAN_FRAME_COUNT != 2U || \
    IRIS_PACKET_HEARTBEAT_CAN_FRAME_COUNT != 1U || \
    IRIS_PACKET_WITNESS_DEBUG_CAN_FRAME_COUNT != 13U || \
    IRIS_PACKET_IRIS_DEBUG_CAN_FRAME_COUNT != 2U
#error "CAN fragmentation counts must match the communications workbook"
#endif
