#pragma once

#include "driver/gpio.h"

// Iris ESP32-C3FH4 board pin map.
// Keep all physical board connections here so application code does not use
// raw GPIO numbers.
#define IRIS_PIN_VSENSE GPIO_NUM_0
#define IRIS_PIN_CAN_TX GPIO_NUM_1
#define IRIS_PIN_BUTTON GPIO_NUM_2
#define IRIS_PIN_CAN_RX GPIO_NUM_3
#define IRIS_PIN_I2C_SDA GPIO_NUM_4
#define IRIS_PIN_I2C_SCL GPIO_NUM_5
#define IRIS_PIN_UART1_TX GPIO_NUM_6
#define IRIS_PIN_UART1_RX GPIO_NUM_7
#define IRIS_PIN_LED_RED GPIO_NUM_8
#define IRIS_PIN_LOAD_SWITCH_ENABLE GPIO_NUM_9
#define IRIS_PIN_LED_GREEN GPIO_NUM_10
#define IRIS_PIN_USB_D_MINUS GPIO_NUM_18
#define IRIS_PIN_USB_D_PLUS GPIO_NUM_19
#define IRIS_PIN_UART0_RX GPIO_NUM_20
#define IRIS_PIN_UART0_TX GPIO_NUM_21

// MCP23008 I/O expander. A2:A0 are tied low, giving address 0x20.
#define IRIS_MCP23008_I2C_ADDRESS 0x20U
#define IRIS_MCP23008_PIN_OUT1_ENABLE 0U
#define IRIS_MCP23008_PIN_OUT2_ENABLE 1U
#define IRIS_MCP23008_PIN_OUT3_ENABLE 2U
#define IRIS_MCP23008_PIN_5V_ENABLE 3U
#define IRIS_MCP23008_PIN_LED_BLUE 7U

#define IRIS_MCP23008_MASK_OUT1_ENABLE \
    (1U << IRIS_MCP23008_PIN_OUT1_ENABLE)
#define IRIS_MCP23008_MASK_OUT2_ENABLE \
    (1U << IRIS_MCP23008_PIN_OUT2_ENABLE)
#define IRIS_MCP23008_MASK_OUT3_ENABLE \
    (1U << IRIS_MCP23008_PIN_OUT3_ENABLE)
#define IRIS_MCP23008_MASK_5V_ENABLE \
    (1U << IRIS_MCP23008_PIN_5V_ENABLE)
#define IRIS_MCP23008_MASK_LED_BLUE \
    (1U << IRIS_MCP23008_PIN_LED_BLUE)

// The expander RESET input shares the LS_EN net.
#define IRIS_PIN_MCP23008_RESET IRIS_PIN_LOAD_SWITCH_ENABLE

