#pragma once

#include "driver/gpio.h"

// RA-01SH-P (SX1262) connections on the Adafruit ESP32-S3 Feather.
#define APERTURE_PIN_RADIO_SPI_SCK GPIO_NUM_5
#define APERTURE_PIN_RADIO_SPI_MOSI GPIO_NUM_18
#define APERTURE_PIN_RADIO_SPI_MISO GPIO_NUM_19
#define APERTURE_PIN_RADIO_CS GPIO_NUM_22
#define APERTURE_PIN_RADIO_RESET GPIO_NUM_33
#define APERTURE_PIN_RADIO_BUSY GPIO_NUM_13
#define APERTURE_PIN_RADIO_DIO1 GPIO_NUM_15
#define APERTURE_PIN_RADIO_RF_ENABLE GPIO_NUM_23

// These settings must match the transmitting radio.
#define APERTURE_RADIO_FREQUENCY_HZ 915000000U
#define APERTURE_RADIO_SPREADING_FACTOR 7U
#define APERTURE_RADIO_BANDWIDTH_HZ 125000U
#define APERTURE_RADIO_CODING_RATE 1U // 4/5
#define APERTURE_RADIO_PREAMBLE_LENGTH 8U

