#pragma once

// AMA command and telemetry protocol definitions from
// "AMA comms standard.xlsx".
// Multi-byte field byte order is defined as big-endian on the wire.

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#define IRIS_COMMAND_ARGUMENT_LENGTH 0U

#define IRIS_COMMAND_CH1_LOAD_OFF 0x30U
#define IRIS_COMMAND_CH1_LOAD_ON 0x31U
#define IRIS_COMMAND_CH2_LOAD_OFF 0x32U
#define IRIS_COMMAND_CH2_LOAD_ON 0x33U
#define IRIS_COMMAND_CH3_LOAD_OFF 0x34U
#define IRIS_COMMAND_CH3_LOAD_ON 0x35U

#define IRIS_COMMAND_5V_REGULATOR_OFF 0x50U
#define IRIS_COMMAND_5V_REGULATOR_ON 0x51U

// ---------------------------------------------------------------------------
// Common packet fields
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_LENGTH 1U
#define IRIS_PACKET_CRC_LENGTH 2U
#define IRIS_PACKET_STATUS_LENGTH 2U
#define IRIS_PACKET_UPTIME_LENGTH 4U

#define IRIS_PACKET_VECTOR_COMPONENTS 3U
#define IRIS_PACKET_QUATERNION_COMPONENTS 4U
#define IRIS_PACKET_CAMERA_CURRENT_CHANNELS 3U

// LoRa packets use the compressed field widths from the workbook.
#define IRIS_LORA_FILTERED_ACCEL_COMPONENT_LENGTH 2U
#define IRIS_LORA_GYRO_COMPONENT_LENGTH 2U
#define IRIS_LORA_ORIENTATION_COMPONENT_LENGTH 3U
#define IRIS_LORA_POSITION_COMPONENT_LENGTH 3U
#define IRIS_LORA_VELOCITY_COMPONENT_LENGTH 2U
#define IRIS_LORA_LATITUDE_LENGTH 3U
#define IRIS_LORA_LONGITUDE_LENGTH 3U
#define IRIS_LORA_GPS_TIME_LENGTH 4U
#define IRIS_LORA_GPS_ALTITUDE_LENGTH 4U
#define IRIS_LORA_MS5607_PRESSURE_LENGTH 2U
#define IRIS_LORA_MS5607_TEMPERATURE_LENGTH 2U
#define IRIS_LORA_MS5607_ALTITUDE_LENGTH 4U
#define IRIS_LORA_WITNESS_BATTERY_VOLTAGE_LENGTH 1U
#define IRIS_LORA_IRIS_BATTERY_VOLTAGE_LENGTH 1U
#define IRIS_LORA_CURRENT_SENSE_COMPONENT_LENGTH 1U
#define IRIS_LORA_COMMAND_LENGTH 2U

// CAN packets use the uncompressed field widths from the workbook.
#define IRIS_CAN_FILTERED_ACCEL_COMPONENT_LENGTH 2U
#define IRIS_CAN_GYRO_COMPONENT_LENGTH 2U
#define IRIS_CAN_ORIENTATION_COMPONENT_LENGTH 4U
#define IRIS_CAN_POSITION_COMPONENT_LENGTH 4U
#define IRIS_CAN_VELOCITY_COMPONENT_LENGTH 4U
#define IRIS_CAN_LATITUDE_LENGTH 3U
#define IRIS_CAN_LONGITUDE_LENGTH 3U
#define IRIS_CAN_GPS_TIME_LENGTH 4U
#define IRIS_CAN_GPS_ALTITUDE_LENGTH 4U
#define IRIS_CAN_MS5607_PRESSURE_LENGTH 3U
#define IRIS_CAN_MS5607_TEMPERATURE_LENGTH 2U
#define IRIS_CAN_MS5607_ALTITUDE_LENGTH 4U
#define IRIS_CAN_WITNESS_BATTERY_VOLTAGE_LENGTH 2U
#define IRIS_CAN_IRIS_BATTERY_VOLTAGE_LENGTH 2U
#define IRIS_CAN_CURRENT_SENSE_COMPONENT_LENGTH 1U
#define IRIS_CAN_COMMAND_LENGTH 2U

// ---------------------------------------------------------------------------
// LoRa sensor packet (10 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_SENSORS 0x01U
#define IRIS_PACKET_SENSORS_DATA_LENGTH \
    (IRIS_PACKET_SENSORS_STATUS_LENGTH + \
     IRIS_PACKET_SENSORS_UPTIME_LENGTH + \
     IRIS_PACKET_SENSORS_ACCEL_LENGTH + \
     IRIS_PACKET_SENSORS_GYRO_LENGTH)
#define IRIS_PACKET_SENSORS_WIRE_LENGTH \
    (IRIS_PACKET_SENSORS_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_SENSORS_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_SENSORS_WIRE_LENGTH)

#define IRIS_PACKET_SENSORS_STATUS_OFFSET 0U
#define IRIS_PACKET_SENSORS_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_SENSORS_UPTIME_OFFSET \
    (IRIS_PACKET_SENSORS_STATUS_OFFSET + \
     IRIS_PACKET_SENSORS_STATUS_LENGTH)
#define IRIS_PACKET_SENSORS_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_SENSORS_ACCEL_OFFSET \
    (IRIS_PACKET_SENSORS_UPTIME_OFFSET + \
     IRIS_PACKET_SENSORS_UPTIME_LENGTH)
#define IRIS_PACKET_SENSORS_ACCEL_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * \
     IRIS_LORA_FILTERED_ACCEL_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_OFFSET \
    (IRIS_PACKET_SENSORS_ACCEL_OFFSET + \
     IRIS_PACKET_SENSORS_ACCEL_LENGTH)
#define IRIS_PACKET_SENSORS_GYRO_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * IRIS_LORA_GYRO_COMPONENT_LENGTH)
#define IRIS_PACKET_SENSORS_CRC_OFFSET IRIS_PACKET_SENSORS_DATA_LENGTH

// ---------------------------------------------------------------------------
// LoRa estimated-state and GPS packet (nominally 2 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_STATE 0x02U
#define IRIS_PACKET_STATE_DATA_LENGTH \
    (IRIS_PACKET_STATE_STATUS_LENGTH + \
     IRIS_PACKET_STATE_UPTIME_LENGTH + \
     IRIS_PACKET_STATE_ORIENTATION_LENGTH + \
     IRIS_PACKET_STATE_POSITION_LENGTH + \
     IRIS_PACKET_STATE_VELOCITY_LENGTH + \
     IRIS_PACKET_STATE_LATITUDE_LENGTH + \
     IRIS_PACKET_STATE_LONGITUDE_LENGTH + \
     IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH + \
     IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH + \
     IRIS_PACKET_STATE_BATTERY_VOLTAGE_LENGTH)
#define IRIS_PACKET_STATE_WIRE_LENGTH \
    (IRIS_PACKET_STATE_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_STATE_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_STATE_WIRE_LENGTH)

#define IRIS_PACKET_STATE_STATUS_OFFSET 0U
#define IRIS_PACKET_STATE_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_STATE_UPTIME_OFFSET \
    (IRIS_PACKET_STATE_STATUS_OFFSET + IRIS_PACKET_STATE_STATUS_LENGTH)
#define IRIS_PACKET_STATE_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_STATE_ORIENTATION_OFFSET \
    (IRIS_PACKET_STATE_UPTIME_OFFSET + IRIS_PACKET_STATE_UPTIME_LENGTH)
#define IRIS_PACKET_STATE_ORIENTATION_LENGTH \
    (IRIS_PACKET_QUATERNION_COMPONENTS * \
     IRIS_LORA_ORIENTATION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_POSITION_OFFSET \
    (IRIS_PACKET_STATE_ORIENTATION_OFFSET + \
     IRIS_PACKET_STATE_ORIENTATION_LENGTH)
#define IRIS_PACKET_STATE_POSITION_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * IRIS_LORA_POSITION_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_OFFSET \
    (IRIS_PACKET_STATE_POSITION_OFFSET + IRIS_PACKET_STATE_POSITION_LENGTH)
#define IRIS_PACKET_STATE_VELOCITY_LENGTH \
    (IRIS_PACKET_VECTOR_COMPONENTS * IRIS_LORA_VELOCITY_COMPONENT_LENGTH)
#define IRIS_PACKET_STATE_LATITUDE_OFFSET \
    (IRIS_PACKET_STATE_VELOCITY_OFFSET + IRIS_PACKET_STATE_VELOCITY_LENGTH)
#define IRIS_PACKET_STATE_LATITUDE_LENGTH IRIS_LORA_LATITUDE_LENGTH
#define IRIS_PACKET_STATE_LONGITUDE_OFFSET \
    (IRIS_PACKET_STATE_LATITUDE_OFFSET + IRIS_PACKET_STATE_LATITUDE_LENGTH)
#define IRIS_PACKET_STATE_LONGITUDE_LENGTH IRIS_LORA_LONGITUDE_LENGTH
#define IRIS_PACKET_STATE_LAT_LON_OFFSET IRIS_PACKET_STATE_LATITUDE_OFFSET
#define IRIS_PACKET_STATE_LAT_LON_LENGTH \
    (IRIS_PACKET_STATE_LATITUDE_LENGTH + IRIS_PACKET_STATE_LONGITUDE_LENGTH)
#define IRIS_PACKET_STATE_GPS_ALTITUDE_OFFSET \
    (IRIS_PACKET_STATE_LONGITUDE_OFFSET + IRIS_PACKET_STATE_LONGITUDE_LENGTH)
#define IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH IRIS_LORA_GPS_ALTITUDE_LENGTH
#define IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_OFFSET \
    (IRIS_PACKET_STATE_GPS_ALTITUDE_OFFSET + \
     IRIS_PACKET_STATE_GPS_ALTITUDE_LENGTH)
#define IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH \
    IRIS_LORA_MS5607_ALTITUDE_LENGTH
#define IRIS_PACKET_STATE_BATTERY_VOLTAGE_OFFSET \
    (IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_OFFSET + \
     IRIS_PACKET_STATE_BAROMETRIC_ALTITUDE_LENGTH)
#define IRIS_PACKET_STATE_BATTERY_VOLTAGE_LENGTH \
    IRIS_LORA_WITNESS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_STATE_CRC_OFFSET IRIS_PACKET_STATE_DATA_LENGTH

// ---------------------------------------------------------------------------
// LoRa camera telemetry packet (1 Hz)
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_CAMERA 0x03U
#define IRIS_PACKET_CAMERA_DATA_LENGTH \
    (IRIS_PACKET_CAMERA_FC_STATUS_LENGTH + \
     IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH + \
     IRIS_PACKET_CAMERA_STATUS_LENGTH + \
     IRIS_PACKET_CAMERA_UPTIME_LENGTH + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH + \
     IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_LENGTH)
#define IRIS_PACKET_CAMERA_WIRE_LENGTH \
    (IRIS_PACKET_CAMERA_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_CAMERA_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_CAMERA_WIRE_LENGTH)

#define IRIS_PACKET_CAMERA_FC_STATUS_OFFSET 0U
#define IRIS_PACKET_CAMERA_FC_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_CAMERA_FC_UPTIME_OFFSET \
    (IRIS_PACKET_CAMERA_FC_STATUS_OFFSET + \
     IRIS_PACKET_CAMERA_FC_STATUS_LENGTH)
#define IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_CAMERA_STATUS_OFFSET \
    (IRIS_PACKET_CAMERA_FC_UPTIME_OFFSET + \
     IRIS_PACKET_CAMERA_FC_UPTIME_LENGTH)
#define IRIS_PACKET_CAMERA_STATUS_LENGTH 2U
#define IRIS_PACKET_CAMERA_UPTIME_OFFSET \
    (IRIS_PACKET_CAMERA_STATUS_OFFSET + IRIS_PACKET_CAMERA_STATUS_LENGTH)
#define IRIS_PACKET_CAMERA_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET \
    (IRIS_PACKET_CAMERA_UPTIME_OFFSET + IRIS_PACKET_CAMERA_UPTIME_LENGTH)
#define IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH \
    (IRIS_PACKET_CAMERA_CURRENT_CHANNELS * \
     IRIS_LORA_CURRENT_SENSE_COMPONENT_LENGTH)
#define IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_OFFSET \
    (IRIS_PACKET_CAMERA_CURRENT_SENSE_OFFSET + \
     IRIS_PACKET_CAMERA_CURRENT_SENSE_LENGTH)
#define IRIS_PACKET_CAMERA_BATTERY_VOLTAGE_LENGTH \
    IRIS_LORA_IRIS_BATTERY_VOLTAGE_LENGTH
#define IRIS_PACKET_CAMERA_CRC_OFFSET IRIS_PACKET_CAMERA_DATA_LENGTH

// ---------------------------------------------------------------------------
// LoRa ground-station heartbeat packet
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_HEARTBEAT 0xFFU
#define IRIS_PACKET_HEARTBEAT_DATA_LENGTH \
    (IRIS_PACKET_HEARTBEAT_STATUS_LENGTH + \
     IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH)
#define IRIS_PACKET_HEARTBEAT_WIRE_LENGTH IRIS_PACKET_HEARTBEAT_DATA_LENGTH
#define IRIS_PACKET_HEARTBEAT_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_HEARTBEAT_WIRE_LENGTH)

#define IRIS_PACKET_HEARTBEAT_STATUS_OFFSET 0U
#define IRIS_PACKET_HEARTBEAT_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_HEARTBEAT_UPTIME_OFFSET \
    (IRIS_PACKET_HEARTBEAT_STATUS_OFFSET + \
     IRIS_PACKET_HEARTBEAT_STATUS_LENGTH)
#define IRIS_PACKET_HEARTBEAT_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH

// ---------------------------------------------------------------------------
// LoRa command packet
// ---------------------------------------------------------------------------

#define IRIS_PACKET_ID_COMMAND 0x05U
#define IRIS_PACKET_COMMAND_STATUS_OFFSET 0U
#define IRIS_PACKET_COMMAND_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_PACKET_COMMAND_UPTIME_OFFSET \
    (IRIS_PACKET_COMMAND_STATUS_OFFSET + IRIS_PACKET_COMMAND_STATUS_LENGTH)
#define IRIS_PACKET_COMMAND_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_PACKET_COMMAND_VALUE_OFFSET \
    (IRIS_PACKET_COMMAND_UPTIME_OFFSET + IRIS_PACKET_COMMAND_UPTIME_LENGTH)
#define IRIS_PACKET_COMMAND_VALUE_LENGTH IRIS_LORA_COMMAND_LENGTH
#define IRIS_PACKET_COMMAND_DATA_LENGTH \
    (IRIS_PACKET_COMMAND_STATUS_LENGTH + \
     IRIS_PACKET_COMMAND_UPTIME_LENGTH + \
     IRIS_PACKET_COMMAND_VALUE_LENGTH)
#define IRIS_PACKET_COMMAND_WIRE_LENGTH \
    (IRIS_PACKET_COMMAND_DATA_LENGTH + IRIS_PACKET_CRC_LENGTH)
#define IRIS_PACKET_COMMAND_FRAME_LENGTH \
    (IRIS_PACKET_ID_LENGTH + IRIS_PACKET_COMMAND_WIRE_LENGTH)
#define IRIS_PACKET_COMMAND_CRC_OFFSET IRIS_PACKET_COMMAND_DATA_LENGTH

// ---------------------------------------------------------------------------
// CAN packet payloads (full-width fields, CRC handled by CAN)
// ---------------------------------------------------------------------------

#define IRIS_CAN_PACKET_CAMERA_STATUS_OFFSET 0U
#define IRIS_CAN_PACKET_CAMERA_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_CAN_PACKET_CAMERA_UPTIME_OFFSET \
    (IRIS_CAN_PACKET_CAMERA_STATUS_OFFSET + \
     IRIS_CAN_PACKET_CAMERA_STATUS_LENGTH)
#define IRIS_CAN_PACKET_CAMERA_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_CAN_PACKET_CAMERA_CURRENT_SENSE_OFFSET \
    (IRIS_CAN_PACKET_CAMERA_UPTIME_OFFSET + \
     IRIS_CAN_PACKET_CAMERA_UPTIME_LENGTH)
#define IRIS_CAN_PACKET_CAMERA_CURRENT_SENSE_LENGTH \
    (IRIS_PACKET_CAMERA_CURRENT_CHANNELS * \
     IRIS_CAN_CURRENT_SENSE_COMPONENT_LENGTH)
#define IRIS_CAN_PACKET_CAMERA_DATA_LENGTH \
    (IRIS_CAN_PACKET_CAMERA_STATUS_LENGTH + \
     IRIS_CAN_PACKET_CAMERA_UPTIME_LENGTH + \
     IRIS_CAN_PACKET_CAMERA_CURRENT_SENSE_LENGTH)

#define IRIS_CAN_PACKET_HEARTBEAT_STATUS_OFFSET 0U
#define IRIS_CAN_PACKET_HEARTBEAT_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_CAN_PACKET_HEARTBEAT_UPTIME_OFFSET \
    (IRIS_CAN_PACKET_HEARTBEAT_STATUS_OFFSET + \
     IRIS_CAN_PACKET_HEARTBEAT_STATUS_LENGTH)
#define IRIS_CAN_PACKET_HEARTBEAT_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_CAN_PACKET_HEARTBEAT_DATA_LENGTH \
    (IRIS_CAN_PACKET_HEARTBEAT_STATUS_LENGTH + \
     IRIS_CAN_PACKET_HEARTBEAT_UPTIME_LENGTH)

#define IRIS_CAN_PACKET_COMMAND_STATUS_OFFSET 0U
#define IRIS_CAN_PACKET_COMMAND_STATUS_LENGTH IRIS_PACKET_STATUS_LENGTH
#define IRIS_CAN_PACKET_COMMAND_UPTIME_OFFSET \
    (IRIS_CAN_PACKET_COMMAND_STATUS_OFFSET + \
     IRIS_CAN_PACKET_COMMAND_STATUS_LENGTH)
#define IRIS_CAN_PACKET_COMMAND_UPTIME_LENGTH IRIS_PACKET_UPTIME_LENGTH
#define IRIS_CAN_PACKET_COMMAND_VALUE_OFFSET \
    (IRIS_CAN_PACKET_COMMAND_UPTIME_OFFSET + \
     IRIS_CAN_PACKET_COMMAND_UPTIME_LENGTH)
#define IRIS_CAN_PACKET_COMMAND_VALUE_LENGTH IRIS_CAN_COMMAND_LENGTH
#define IRIS_CAN_PACKET_COMMAND_DATA_LENGTH \
    (IRIS_CAN_PACKET_COMMAND_STATUS_LENGTH + \
     IRIS_CAN_PACKET_COMMAND_UPTIME_LENGTH + \
     IRIS_CAN_PACKET_COMMAND_VALUE_LENGTH)

// Catch accidental schema drift from the workbook totals. These lengths do
// not include a packet ID or application-level CRC.
#if IRIS_PACKET_SENSORS_DATA_LENGTH != 18U
#error "LoRa sensor packet length must be 18 bytes"
#endif
#if IRIS_PACKET_STATE_DATA_LENGTH != 48U
#error "LoRa state packet length must be 48 bytes"
#endif
#if IRIS_PACKET_CAMERA_DATA_LENGTH != 16U
#error "LoRa camera packet length must be 16 bytes"
#endif
#if IRIS_PACKET_HEARTBEAT_DATA_LENGTH != 6U
#error "LoRa heartbeat packet length must be 6 bytes"
#endif
#if IRIS_PACKET_COMMAND_DATA_LENGTH != 8U
#error "LoRa command packet length must be 8 bytes"
#endif
#if IRIS_CAN_PACKET_CAMERA_DATA_LENGTH != 9U
#error "CAN camera packet length must be 9 bytes"
#endif
#if IRIS_CAN_PACKET_HEARTBEAT_DATA_LENGTH != 6U
#error "CAN heartbeat packet length must be 6 bytes"
#endif
#if IRIS_CAN_PACKET_COMMAND_DATA_LENGTH != 8U
#error "CAN command packet length must be 8 bytes"
#endif
